### ISSUE TITLE
Problems with PostgreSQL

### ISSUE THREAD

**Issue by ldidry** [ganigeorgiev/presentator#74]
Hello,

I installed presentator (latest release) with a PostgreSQL database (9.6).

First problem: I'm unable to create or view a project. 

```
2018-07-30 15:05:45 [2001:913:c09:1337:148c:c124:1314:fe1d][4][5lll0h3k1o4cl7hfks1mgglhq5][error][yii\db\Exception] PDOException: SQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne userSetting.userid n'existe pas
LINE 1: ...= "screenComment".from LEFT JOIN "userSetting" ON "userSetti...
                                                             ^
HINT:  Peut-être que vous souhaitiez référencer la colonne « userSetting.userId ». in /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php:1067
Stack trace:
#0 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php(1067): PDOStatement->execute()
#1 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php(386): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Query.php(217): yii\db\Command->queryAll()
#3 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#4 /var/www/clients/client1/web26/web/common/models/ProjectQueryTrait.php(131): yii\db\ActiveQuery->all()
#5 /var/www/clients/client1/web26/web/app/controllers/MentionsTrait.php(24): common\models\Project->findAllCommenters()
#6 /var/www/clients/client1/web26/web/app/controllers/ProjectsController.php(87): app\controllers\ProjectsController->getMentionsList(Object(common\models\Project))
#7 [internal function]: app\controllers\ProjectsController->actionView('1')
#8 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('view', Array)
#11 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('projects/view', Array)
#12 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 /var/www/clients/client1/web26/web/app/web/index.php(17): yii\base\Application->run()
#14 {main}
```

That is easily solved by doublequoting the table name in `common/models/ProjectQueryTrait.php` (line 113):

```
sprintf('%s."userId" = %s.id', UserSetting::tableName(), User::tableName())
```

Then I encounter another problem, when trying to create a new version of a project:
```
2018-07-30 15:16:31 [2001:913:c09:1337:148c:c124:1314:fe1d][4][5lll0h3k1o4cl7hfks1mgglhq5][error][yii\db\Exception] PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour l'entier : «  » in /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php:1067
Stack trace:
#0 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php(1067): PDOStatement->execute()
#1 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Command.php(400): yii\db\Command->queryInternal('fetch', NULL)
#2 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/Query.php(259): yii\db\Command->queryOne()
#3 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/db/ActiveQuery.php(292): yii\db\Query->one(NULL)
#4 /var/www/clients/client1/web26/web/common/models/ProjectQueryTrait.php(22): yii\db\ActiveQuery->one()
#5 /var/www/clients/client1/web26/web/app/controllers/VersionsController.php(92): common\models\Project->findVersionById('')
#6 [internal function]: app\controllers\VersionsController->actionAjaxGetForm('1', '')
#7 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('ajax-get-form', Array)
#10 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('versions/ajax-g...', Array)
#11 /var/www/clients/client1/web26/web/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /var/www/clients/client1/web26/web/app/web/index.php(17): yii\base\Application->run()
#13 {main}
```

The problem is still in `common/models/ProjectQueryTrait.php`, but in `findVersionById` function: it tries to make a SQL request with an empty string as `id` value. I managed to solve it by adding
```
        if ($versionId == '') {
            $versionId = null;
        }
```
before the query.

I know that my hacks are dirty, but they work and they may give a hint about how to solve the problems properly.

**Comment by ganigeorgiev** [comment]
@ldidry Should be fixed in v1.10.0 (tested with PostgreSQL v9.6 and v10.4).
